import Head from 'next/head'

import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Michael Corbo's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-emerald-900 text-gray-300">
        <section>
          <nav className='py-5 flex justify-between'>
            <h1 className='text-l'>Corbo Customs</h1>
            <ul className='flex'>
              <li></li>
              <li className='hover:text-xl'><a href='#about'>About</a></li>
              <li className='hover:text-xl'><a href='#projects'>Projects</a></li>
              <li className='hover:text-xl'><a href='#contact'>Contact</a></li>
            </ul>
          </nav>
          

        </section>
      </main>
    </>
  )
}
